apiVersion: accelerator.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: "knative-function"
spec:
  displayName: Spring Cloud Function App for Knative
  description: A simple Spring Cloud Function-based serverless app with JVM/Native image compilation for deploying on Knative/Cloud Native Runtime
  iconUrl: https://raw.githubusercontent.com/simple-starters/icons/master/icon-cloud.png
  tags:
    - spring
    - cloud
    - function
    - serverless
    - native
  git:
    url: "https://github.com/ddobrin/spring-native-function-knative"
    ref:
      branch: "main"
